# -*- coding: utf-8 -*-
"""canser.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zbNHOTXvSMUtUm_d_I1DlhmQriHts5VJ
"""

import pandas as pd

dataset = pd.read_csv("cancer.csv")

x = dataset.drop(columns=['diagnosis(1=m, 0=b)'])

y = dataset['diagnosis(1=m, 0=b)']

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

import tensorflow as tf

model = tf.keras.models.Sequential()

model.add(tf.keras.layers.Dense(256, input_shape=x_train.shape[1:], activation='sigmoid'))
model.add(tf.keras.layers.Dense(256, activation='sigmoid'))
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics='accuracy')
print("model print \n",model)
print(x_train)
print(y_train)

model.fit(x_train, y_train, epochs=100)

model.evaluate(x_test, y_test)

"""jupyter notebook --NotebookApp.allow_origin='https://colab.research.google.com' --port=8888 --NotebookApp.port_retries=0"""

